input_path: ../data/example.zarr/seg/s0
output_directory: ../output
num_workers: 1

do_simplification: true
target_reduction: 0.5
n_smoothing_iter: 5
check_mesh_validity: false

do_multires: true
num_lods: 3
multires_strategy: decimate
decimation_factor: 2
delete_decimated_meshes: true
